# frozen_string_literal: true

require "optparse"

module SymphonyRuby
  class CLI
    def self.start(argv)
      new(argv).start
    end

    def initialize(argv)
      @argv = argv.dup
      @once = false
    end

    def start
      parser.parse!(@argv)
      workflow = @argv.shift || "WORKFLOW.md"
      puts "[symphony-ruby] Loading workflow: #{File.expand_path(workflow)}"
      config = Config.load(workflow)
      puts "[symphony-ruby] GitHub project: owner=#{config.github.owner} owner_type=#{config.github.owner_type} project_number=#{config.github.project_number}"
      puts "[symphony-ruby] GitHub token source: #{config.github.token_source}#{config.github.token.empty? ? " (empty)" : ""}"
      puts "[symphony-ruby] Ticket filter: #{config.ticket.status_field}=#{config.ticket.ready_status}"
      puts "[symphony-ruby] Workspace root: #{config.workspace.root}"
      puts "[symphony-ruby] Agent: provider=#{config.agent.provider} model=#{config.agent.model} max_concurrent=#{config.agent.max_concurrent_agents}"
      tracker = tracker_for(config)
      orchestrator = Orchestrator.new(config: config, tracker: tracker)
      @once ? orchestrator.run_once : orchestrator.run_forever
      0
    rescue OptionParser::ParseError, ArgumentError => error
      warn "symphony-ruby: #{error.message}"
      warn parser
      64
    end

    private

    def parser
      @parser ||= OptionParser.new do |opts|
        opts.banner = "Usage: symphony-ruby [WORKFLOW.md] [options]"
        opts.on("--once", "Poll once and exit") { @once = true }
        opts.on("--version", "Print version") do
          puts VERSION
          exit 0
        end
      end
    end

    def tracker_for(config)
      dry = ENV["SYMPHONY_DRY_RUN_TICKET"]
      unless dry
        return GithubProjectsTracker.new(
          config: config,
          client: GithubProjectsClient.new(token: config.github.token, logger: $stdout)
        )
      end

      puts "[symphony-ruby] Using dry-run ticket from SYMPHONY_DRY_RUN_TICKET"
      identifier, title = dry.split("|", 2)
      DryRunTracker.new(Ticket.new(
        id: "dry-run",
        content_id: "",
        identifier: identifier || "DRY-1",
        labels: [],
        title: title || "Dry run ticket",
        body: "Generated by SYMPHONY_DRY_RUN_TICKET",
        url: "",
        status: config.ticket.ready_status,
        repository: "",
        fields: { config.ticket.status_field => config.ticket.ready_status }
      ))
    end
  end

  class DryRunTracker
    def initialize(ticket)
      @ticket = ticket
    end

    def fetch_ready_tickets
      [@ticket]
    end

    def mark_in_progress(_ticket); end
  end
end
