# frozen_string_literal: true

module SymphonyRuby
  class GitManager
    def initialize(workspace:, logger: $stdout)
      @workspace = workspace
      @logger = logger
    end

    def finalize(ticket)
      return false unless git_repo?

      trace "Committing changes for #{ticket.identifier}"

      commit_all(ticket)
      branch_name = branch_name_for(ticket)
      create_branch(branch_name)
      remote = push_remote(ticket)
      push_branch(remote, branch_name)
      create_pr(ticket, branch_name)
      true
    end

    private

    def branch_name_for(ticket)
      number = ticket.identifier.to_s.gsub(/^#/, "")
      slug = slugify(ticket.title)
      "#{number}-#{slug}".gsub(/--+/, "-").gsub(/-+\z/, "")
    end

    def slugify(text)
      text.to_s
          .downcase
          .gsub(/[^a-z0-9]+/, "-")
          .gsub(/\A-+|-+\z/, "")
          .slice(0, 60)
    end

    def commit_all(ticket)
      return if clean?

      run("git", "add", "-A")
      run("git", "commit", "-m", commit_message(ticket))
    end

    def create_branch(branch_name)
      run("git", "checkout", "-b", branch_name)
    end

    def push_branch(remote, branch_name)
      run("git", "push", "-u", remote, branch_name)
    end

    def create_pr(ticket, branch_name)
      args = ["gh", "pr", "create",
              "--title", ticket.title,
              "--body", pr_body(ticket),
              "--base", "main",
              "--head", branch_name]
      args += ["--repo", ticket.repository] if github_repository?(ticket.repository)

      run(*args)
    end

    def push_remote(ticket)
      return "origin" if github_remote?(remote_url("origin"))

      return "origin" unless github_repository?(ticket.repository)

      ensure_remote("symphony-pr", "git@github.com:#{ticket.repository}.git")
      "symphony-pr"
    end

    def ensure_remote(name, url)
      existing_url = remote_url(name)

      if existing_url.nil?
        run("git", "remote", "add", name, url)
      elsif existing_url != url
        run("git", "remote", "set-url", name, url)
      end
    end

    def remote_url(name)
      stdout, _stderr, status = Open3.capture3("git", "remote", "get-url", name, chdir: @workspace)
      return nil unless status.success?

      stdout.strip
    end

    def github_remote?(url)
      url.to_s.match?(%r{\A(?:git@|https://|ssh://git@)github\.com[:/]})
    end

    def github_repository?(repository)
      repository.to_s.match?(%r{\A[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+\z})
    end

    def commit_message(ticket)
      number = ticket.identifier.to_s.gsub(/^#/, "")
      "feat(##{number}): #{ticket.title}\n\n#{ticket.body}\n\nCloses ##{number}"
    end

    def pr_body(ticket)
      number = ticket.identifier.to_s.gsub(/^#/, "")
      <<~BODY.strip
        Closes ##{number}

        #{ticket.body}

        ---
        _Generated by symphony-ruby_
      BODY
    end

    def clean?
      `git -C #{Shellwords.escape(@workspace)} status --porcelain`.strip.empty?
    end

    def git_repo?
      system("git", "-C", @workspace, "rev-parse", "--git-dir", out: File::NULL, err: File::NULL)
    end

    def run(*args)
      trace(*args)
      system(*args, chdir: @workspace, exception: true)
    end

    def trace(*args)
      @logger.puts "[symphony-ruby] #{args.join(' ')}"
    end
  end
end
