# frozen_string_literal: true

module SymphonyRuby
  class GitManager
    def initialize(workspace:, logger: $stdout)
      @workspace = workspace
      @logger = logger
    end

    def finalize(ticket)
      return false unless git_repo?

      trace "Committing changes for #{ticket.identifier}"

      commit_all(ticket)
      branch_name = branch_name_for(ticket)
      create_branch(branch_name)
      push_branch(branch_name)
      create_pr(ticket, branch_name)
      true
    end

    private

    def branch_name_for(ticket)
      number = ticket.identifier.to_s.gsub(/^#/, "")
      slug = slugify(ticket.title)
      "#{number}-#{slug}".gsub(/--+/, "-").gsub(/-+\z/, "")
    end

    def slugify(text)
      text.to_s
          .downcase
          .gsub(/[^a-z0-9]+/, "-")
          .gsub(/\A-+|-+\z/, "")
          .slice(0, 60)
    end

    def commit_all(ticket)
      return if clean?

      run("git", "add", "-A")
      run("git", "commit", "-m", commit_message(ticket))
    end

    def create_branch(branch_name)
      run("git", "checkout", "-b", branch_name)
    end

    def push_branch(branch_name)
      run("git", "push", "-u", "origin", branch_name)
    end

    def create_pr(ticket, branch_name)
      run("gh", "pr", "create",
          "--title", ticket.body.empty? ? ticket.title : ticket.title,
          "--body", pr_body(ticket),
          "--base", "main")
    end

    def commit_message(ticket)
      number = ticket.identifier.to_s.gsub(/^#/, "")
      "feat(##{number}): #{ticket.title}\n\n#{ticket.body}\n\nCloses ##{number}"
    end

    def pr_body(ticket)
      number = ticket.identifier.to_s.gsub(/^#/, "")
      <<~BODY.strip
        Closes ##{number}

        #{ticket.body}

        ---
        _Generated by symphony-ruby_
      BODY
    end

    def clean?
      `git -C #{Shellwords.escape(@workspace)} status --porcelain`.strip.empty?
    end

    def git_repo?
      system("git", "-C", @workspace, "rev-parse", "--git-dir", out: File::NULL, err: File::NULL)
    end

    def run(*args)
      trace(*args)
      system(*args, chdir: @workspace, exception: true)
    end

    def trace(*args)
      @logger.puts "[symphony-ruby] #{args.join(' ')}"
    end
  end
end
